const Sequelize = require('sequelize');
const db = require('../database');

const { INTEGER, ENUM } = Sequelize;

const OrderStatuses = db.define(
  'orderStatuses',
  {
    //Changed the min from 0 to 1 because having 0 may not be good practice as it may also be used to denote a null value
    //If id was something like statusID rather than the usual autogenerated pk (starting from 1,2,3,4...) then 0 would be okay. But just to keep things simple I think changing id start value from 0 to 1 would be better.
    id: {
      type: INTEGER,
      primaryKey: true,
      validate: {
        min: 1,
        max: 4
      }
    },
    status: {
      type: ENUM,
      values: [
        'open', // 1
        'ordered', // 2
        'shipped', // 3
        'delivered' // 4
      ],
      allowNull: false,
      validate: {
        notEmpty: true
      }
    }
  },
  //Added this to removed the createdDate and updatedDate columns from these reference tables since those would be of no use. But, if someone prefers to have those columns there please feel free to remove it from the reference tables :)
  { timestamps: false }
);

module.exports = OrderStatuses;
